craft-applications:
  - name: charmcraft
    branches:
      - main
      - hotfix/*
  - name: rockcraft
    branches:
      - main
      - hotfix/*
  - name: snapcraft
    branches:
      - main
      - hotfix/*

craft-libraries:
  - craft-application
  - craft-archives
  - craft-cli
  - craft-grammar
  - craft-parts
  - craft-platforms
  - craft-providers
  - craft-store

craft-projects:
  - charmcraft
  - craft-application
  - craft-archives
  - craft-cli
  - craft-grammar
  - craft-parts
  - craft-platforms
  - craft-providers
  - craft-store
  - rockcraft
  - snapcraft
  - starbase
