name: github batch 2
on:
  schedule:
    - cron: '05 5 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: install dependencies
        run: pip install .
      - name: collect data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          starcraft-stats github canonical craft-cli
          starcraft-stats github canonical craft-grammar
          starcraft-stats github canonical craft-parts
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: update craft-cli, craft-grammar, craft-parts data"
