name: github batch 3
on:
  schedule:
    - cron: '10 6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: install application
        run: pip install .
      - name: collect data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          starcraft-stats github canonical craft-providers
          starcraft-stats github canonical craft-store
          starcraft-stats github canonical rockcraft
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: update craft-providers, craft-store, rockcraft"
