name: github batch 1
on:
  schedule:
    - cron: '00 4 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: install project
        run: pip install .
      - name: collect data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          starcraft-stats fetch-reqs
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: fetch craft applications & libraries"
